function onCreateUser(){var e=document.getElementById("info_form"),t=document.getElementById("create_form")
e.style.display="none",t.style.display=""}function onCancelCreateUser(){var e=document.getElementById("info_form"),t=document.getElementById("create_form")
e.style.display="",t.style.display="none"}function activate_intput(){var e=document.getElementById("info_name"),t=document.getElementById("edit_btn")
e.readonly="",e.disabled=!1,t.style.display="none"}function onChangeUserName(){const e=getSelectedUserJson()
var t=document.getElementById("info_name"),n=e.info.name,l=t.value,a=getAllUserName()
if(a.includes(l))alert("用户名已存在!无法修改"),location.reload()
else{var o=window.confirm("是否修改用户名: ["+n+"] --> ["+l+"]")
o===!0?(e.info.name=l,deleteUser(n),createUser(l,e),location.reload()):console.log("取消覆盖!")}}function edit_page_onload(){all_page_onload()
var e=document.getElementById("info_name"),t=document.getElementById("edit_dbtn")
const n=getSelectedUserJson()
e.value=n.info.name,e.disabled=!0,n.is_default&&(t.style.display="none"),init_language()}function setDefaultUser(){const e=getSelectedUserJson()
e.is_default||(e.is_default=!0,cancelDefaultOtherUser(),saveUserJson(e.info.name,e),location.reload())}function onResetUser(){const e=getSelectedUserJson()
createUser(e.info.name,{})}function onDeleteUser(){const e=getSelectedUserJson()
deleteUser(e.info.name)}function onSaveUser(){var e=document.getElementById("create_name"),t=getAllUserName()
null!=e.value&&""!==e.value&&(t.includes(e.value)?(e.placeholder="用户名已存在: ["+e.value+"]",e.value=""):(createUser(e.value,{}),location.reload()))}