function onCreateUser(){var e=document.getElementById("info_form"),n=document.getElementById("create_form")
e.style.display="none",n.style.display=""}function onCancelCreateUser(){var e=document.getElementById("info_form"),n=document.getElementById("create_form")
e.style.display="",n.style.display="none"}function activate_intput(){var e=document.getElementById("info_name"),n=document.getElementById("edit_btn")
e.readonly="",e.disabled=!1,n.style.display="none"}function onChangeUserName(){const e=getSelectedUserJson()
var n=document.getElementById("info_name"),t=e.info.name,o=n.value,l=getAllUserName()
if(l.includes(o))alert("用户名已存在!无法修改"),location.reload()
else{var a=window.confirm("是否修改用户名: ["+t+"] --> ["+o+"]")
a===!0?(e.info.name=o,deleteUser(t),createUser(o,e),location.reload()):console.log("取消覆盖!")}}function edit_page_onload(){all_page_onload()
var e=document.getElementById("info_name"),n=document.getElementById("edit_dbtn")
const t=getSelectedUserJson()
e.value=t.info.name,e.disabled=!0,t.is_default&&(n.style.display="none"),init_language()}function setDefaultUser(){const e=getSelectedUserJson()
e.is_default||(e.is_default=!0,cancelDefaultOtherUser(),saveUserJson(e.info.name,e),location.reload())}function onResetUser(){const e=getSelectedUserJson()
createUser(e.info.name)}function onDeleteUser(){const e=getSelectedUserJson()
deleteUser(e.info.name)}function onSaveUser(){var e=document.getElementById("create_name"),n=getAllUserName()
null!=e.value&&""!==e.value&&(n.includes(e.value)?(e.placeholder="用户名已存在: ["+e.value+"]",e.value=""):(createUser(e.value),location.reload()))}